### PR TITLE
@ implode() error preventing setup from completing

### PR DESCRIPTION
**Pull request by BuenGenio**

### CODE REVIEW

**Comment by sampoyigi** [comment]
Any information on the error?

**Comment by BuenGenio** [comment]
Yes, sorry - this is an old "fix" for installer quitting when display_errors and error_reporting are configured for debugging...

18 Jul 2020 21:41:05 Sam Poyigi <notifications@github.com>:

**Comment by sampoyigi** [comment]
Do you have a full stack trace to the error? Or something to help reproduce the error?

**Comment by sampoyigi** [comment]
Closed due to no response.

**Pull request closed without merging**
